---

- name: SETTING UP THE SERVER FOR WORDPRESS
  gather_facts: false
  become: true
  hosts: wordpress-srv

  tasks:
    - name: UPDATE REPOSITORIES CACHE
      ansible.builtin.apt:
       update_cache: yes

    - name: UPGRADE PACKAGES
      ansible.builtin.apt:
        upgrade: yes
      notify: reboot_system

    - name: INSTALL ALL NECESSARY PACKAGES
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - docker.io
        - docker-compose-v2
        - unattended-upgrades
      notify: reboot_system

    - meta: flush_handlers

    - name: GRANTING DOCKER ACCESS TO USER WORDPRESS
      ansible.builtin.user:
        name: wordpress
        groups: docker

    - name: COPY THE NECESSARY FILES
      ansible.builtin.copy:
        src: docker-compose.yaml
        dest: /home/wordpress/
        mode: '0700'
        owner: 'wordpress'
        group: 'wordpress'

    - name: CREATE AND START SERVICES USING DOCKER COMPOSE
      community.docker.docker_compose_v2:
        project_src: /home/wordpress/

  handlers:
  - name: reboot_system
    ansible.builtin.reboot:
      reboot_timeout: 30
