version: '3'
 
services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - wpsite


  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 80:80
    restart: always
    volumes: [./:/var/www/html]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 8080:80
    networks:
      - wpsite


volumes:
  dbdata:
  portainer_data:

networks:
  wpsite: